#!/usr/bin/php
<?php

declare(strict_types=1);

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Afaya\EdgeTTS\CLI\SynthesizeCommand;
use Afaya\EdgeTTS\CLI\VoiceListCommand;

$application = new Application('Edge TTS CLI', '1.0.1');

$application->addCommands([
    new SynthesizeCommand(),
    new VoiceListCommand(),
]);

try {
    $application->run();
} catch (\Exception $e) {
    fwrite(STDERR, 'Error: ' . $e->getMessage() . PHP_EOL);
    exit(1);
}
